# -*- coding: utf-8 -*-
"""03_feature_selection_and_diagnostics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14RQnzyOw7409cEVDMkj_8mynT9xS5s_E
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np

DATA_DIR = '/content/drive/MyDrive/MIRAGE/data/raw/GSE98320'

clean_df = pd.read_csv(f'{DATA_DIR}/gse98320_master_pathology_labels.csv')
gene_expr_matrix = pd.read_parquet(f'{DATA_DIR}/gse98320_gene_expression.parquet')

print("Master table shape:", clean_df.shape)
print("Confirms cv_fold present:", 'cv_fold' in clean_df.columns)
print(clean_df['cv_fold'].value_counts().sort_index())

banff_cols = ['g', 'cg', 'i', 'ci', 't', 'ct', 'v', 'cv', 'ah', 'ptc', 'c4d_ordinal']
print("\nMissingness per Banff column (overall, for reference only):")
print(clean_df[banff_cols].isna().sum())

def preprocess_pathology_fold(clean_df, banff_cols, train_idx, val_idx):
    """
    Fit median imputation on training rows only, apply to both train and val.
    Adds a missingness indicator column per Banff variable before imputing.
    Returns two DataFrames: processed train and val pathology feature sets.
    """
    train_df = clean_df.loc[train_idx, banff_cols].copy()
    val_df = clean_df.loc[val_idx, banff_cols].copy()

    # Step 1: missingness indicators (built from raw NaN pattern, before imputation)
    for col in banff_cols:
        train_df[f'{col}_was_missing'] = train_df[col].isna().astype(int)
        val_df[f'{col}_was_missing'] = val_df[col].isna().astype(int)

    # Step 2: median imputation, fit on train only
    medians = train_df[banff_cols].median()

    for col in banff_cols:
        train_df[col] = train_df[col].fillna(medians[col])
        val_df[col] = val_df[col].fillna(medians[col])  # note: val uses TRAIN medians, never its own

    return train_df, val_df, medians


# Quick test on fold 0 to confirm it works as expected
fold0_train_idx = clean_df[clean_df['cv_fold'] != 0].index
fold0_val_idx = clean_df[clean_df['cv_fold'] == 0].index

train_processed, val_processed, fold0_medians = preprocess_pathology_fold(
    clean_df, banff_cols, fold0_train_idx, fold0_val_idx
)

print("Train processed shape:", train_processed.shape)
print("Val processed shape:", val_processed.shape)
print("\nAny remaining NaN in train?", train_processed.isna().sum().sum())
print("Any remaining NaN in val?", val_processed.isna().sum().sum())
print("\nFold 0 training medians used for imputation:")
print(fold0_medians)

train_processed.head()

fold_data = {}  # will store {fold_idx: {'X_pathology_train':..., 'X_gene_train':..., 'y_train':..., ...}}

for fold in range(5):
    train_idx = clean_df[clean_df['cv_fold'] != fold].index
    val_idx = clean_df[clean_df['cv_fold'] == fold].index

    # --- Pathology: median impute + missingness indicators ---
    path_train, path_val, medians = preprocess_pathology_fold(clean_df, banff_cols, train_idx, val_idx)

    # --- Gene expression: per-fold z-score standardization ---
    train_gsms = clean_df.loc[train_idx, 'GSM'].values
    val_gsms = clean_df.loc[val_idx, 'GSM'].values

    gene_train_raw = gene_expr_matrix[train_gsms].T  # samples x genes
    gene_val_raw = gene_expr_matrix[val_gsms].T

    gene_means = gene_train_raw.mean(axis=0)
    gene_stds = gene_train_raw.std(axis=0).replace(0, 1)  # avoid divide-by-zero for zero-variance genes

    gene_train_scaled = (gene_train_raw - gene_means) / gene_stds
    gene_val_scaled = (gene_val_raw - gene_means) / gene_stds

    # --- Labels ---
    y_train = clean_df.loc[train_idx, 'mirage_label'].values
    y_val = clean_df.loc[val_idx, 'mirage_label'].values

    fold_data[fold] = {
        'path_train': path_train, 'path_val': path_val,
        'gene_train': gene_train_scaled, 'gene_val': gene_val_scaled,
        'y_train': y_train, 'y_val': y_val,
        'train_gsms': train_gsms, 'val_gsms': val_gsms,
    }

    print(f"Fold {fold}: train={len(train_idx)}, val={len(val_idx)}, "
          f"gene_train shape={gene_train_scaled.shape}, "
          f"any NaN in gene_train={gene_train_scaled.isna().sum().sum()}")

print("\nAll 5 folds processed and stored in fold_data dict.")

from sklearn.feature_selection import f_classif

def select_genes_two_stage(gene_train_df, y_train, variance_top_n=5000, k_final=1000):
    """
    Stage 1: keep the variance_top_n highest-variance genes (fit on train only).
    Stage 2: from those, keep the k_final genes with the highest ANOVA F-statistic
             w.r.t. the class labels (fit on train only).
    Returns the list of selected gene names.
    """
    # Stage 1: variance filter
    gene_variances = gene_train_df.var(axis=0)
    top_variance_genes = gene_variances.nlargest(variance_top_n).index

    # Stage 2: ANOVA F-test on the survivors
    X_stage1 = gene_train_df[top_variance_genes]
    f_scores, p_values = f_classif(X_stage1, y_train)

    f_score_series = pd.Series(f_scores, index=top_variance_genes)
    selected_genes = f_score_series.nlargest(k_final).index.tolist()

    return selected_genes


# Quick test on fold 0 with a placeholder k_final
test_genes = select_genes_two_stage(
    fold_data[0]['gene_train'], fold_data[0]['y_train'],
    variance_top_n=5000, k_final=1000
)

print(f"Selected {len(test_genes)} genes")
print("First 10:", test_genes[:10])

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score
import time

k_candidates = [100, 250, 500, 1000, 2000]
variance_top_n = 5000  # fixed stage-1 filter size

results = []

for k in k_candidates:
    fold_f1_scores = []
    start = time.time()

    for fold in range(5):
        gene_train = fold_data[fold]['gene_train']
        gene_val = fold_data[fold]['gene_val']
        y_train = fold_data[fold]['y_train']
        y_val = fold_data[fold]['y_val']

        selected_genes = select_genes_two_stage(gene_train, y_train, variance_top_n=variance_top_n, k_final=k)

        X_train_k = gene_train[selected_genes]
        X_val_k = gene_val[selected_genes]

        clf = RandomForestClassifier(n_estimators=200, class_weight='balanced', random_state=42, n_jobs=-1)
        clf.fit(X_train_k, y_train)
        preds = clf.predict(X_val_k)

        macro_f1 = f1_score(y_val, preds, average='macro')
        fold_f1_scores.append(macro_f1)

    mean_f1 = np.mean(fold_f1_scores)
    std_f1 = np.std(fold_f1_scores)
    elapsed = time.time() - start

    results.append({'k': k, 'mean_macro_f1': mean_f1, 'std_macro_f1': std_f1, 'fold_scores': fold_f1_scores})
    print(f"K={k}: mean macro-F1={mean_f1:.4f} (+/- {std_f1:.4f})  [{elapsed:.1f}s]")

results_df = pd.DataFrame(results)
results_df

from sklearn.metrics import classification_report

# Use K=500 (best mean) and K=1000 (most stable) for a closer look
for k in [500, 1000]:
    print(f"\n{'='*50}\nK={k} — per-class F1 across folds\n{'='*50}")

    for fold in range(5):
        gene_train = fold_data[fold]['gene_train']
        gene_val = fold_data[fold]['gene_val']
        y_train = fold_data[fold]['y_train']
        y_val = fold_data[fold]['y_val']

        selected_genes = select_genes_two_stage(gene_train, y_train, variance_top_n=5000, k_final=k)
        X_train_k = gene_train[selected_genes]
        X_val_k = gene_val[selected_genes]

        clf = RandomForestClassifier(n_estimators=200, class_weight='balanced', random_state=42, n_jobs=-1)
        clf.fit(X_train_k, y_train)
        preds = clf.predict(X_val_k)

        print(f"\n--- Fold {fold} ---")
        print(classification_report(y_val, preds, zero_division=0))

final_k = 1000
selected_genes_per_fold = {}

for fold in range(5):
    gene_train = fold_data[fold]['gene_train']
    y_train = fold_data[fold]['y_train']

    selected_genes = select_genes_two_stage(gene_train, y_train, variance_top_n=5000, k_final=final_k)
    selected_genes_per_fold[fold] = selected_genes

    print(f"Fold {fold}: {len(selected_genes)} genes selected")

# Save as JSON so it's reusable across notebooks/models without recomputation
import json

genes_output_path = f'{DATA_DIR}/selected_genes_per_fold_k1000.json'
with open(genes_output_path, 'w') as f:
    json.dump(selected_genes_per_fold, f)

print(f"\nSaved to {genes_output_path}")

from sklearn.metrics import confusion_matrix
import json

with open(f'{DATA_DIR}/selected_genes_per_fold_k1000.json', 'r') as f:
    selected_genes_per_fold = json.load(f)

class_labels = ['NR', 'TCMR', 'ABMR', 'Mixed']  # fixed order for consistent matrix axes

all_y_true = []
all_y_pred = []

for fold in range(5):
    gene_train = fold_data[fold]['gene_train']
    gene_val = fold_data[fold]['gene_val']
    y_train = fold_data[fold]['y_train']
    y_val = fold_data[fold]['y_val']

    selected_genes = selected_genes_per_fold[str(fold)]  # JSON keys become strings

    X_train_k = gene_train[selected_genes]
    X_val_k = gene_val[selected_genes]

    clf = RandomForestClassifier(n_estimators=200, class_weight='balanced', random_state=42, n_jobs=-1)
    clf.fit(X_train_k, y_train)
    preds = clf.predict(X_val_k)

    all_y_true.extend(y_val)
    all_y_pred.extend(preds)

cm = confusion_matrix(all_y_true, all_y_pred, labels=class_labels)
cm_df = pd.DataFrame(cm, index=[f'true_{c}' for c in class_labels], columns=[f'pred_{c}' for c in class_labels])

print("Aggregated confusion matrix across all 5 folds:")
print(cm_df)

print("\nAs row-normalized percentages (what fraction of each true class went where):")
cm_pct = cm_df.div(cm_df.sum(axis=1), axis=0).round(3) * 100
print(cm_pct)

from sklearn.metrics import recall_score, precision_score

# Binary relabeling: NR vs Rejection (everything else)
def to_binary_rejection(y):
    return np.array(['NR' if label == 'NR' else 'Rejection' for label in y])

binary_results = []

for fold in range(5):
    gene_train = fold_data[fold]['gene_train']
    gene_val = fold_data[fold]['gene_val']
    y_train = fold_data[fold]['y_train']
    y_val = fold_data[fold]['y_val']

    selected_genes = selected_genes_per_fold[str(fold)]
    X_train_k = gene_train[selected_genes]
    X_val_k = gene_val[selected_genes]

    y_train_bin = to_binary_rejection(y_train)
    y_val_bin = to_binary_rejection(y_val)

    clf = RandomForestClassifier(n_estimators=200, class_weight='balanced', random_state=42, n_jobs=-1)
    clf.fit(X_train_k, y_train_bin)
    preds = clf.predict(X_val_k)

    rejection_recall = recall_score(y_val_bin, preds, pos_label='Rejection')
    rejection_precision = precision_score(y_val_bin, preds, pos_label='Rejection')

    binary_results.append({'fold': fold, 'rejection_recall': rejection_recall, 'rejection_precision': rejection_precision})
    print(f"Fold {fold}: Rejection recall={rejection_recall:.3f}, precision={rejection_precision:.3f}")

binary_df = pd.DataFrame(binary_results)
print(f"\nMean rejection recall: {binary_df['rejection_recall'].mean():.3f}")
print(f"Mean rejection precision: {binary_df['rejection_precision'].mean():.3f}")

from sklearn.feature_selection import f_classif

def select_genes_binary_focused(gene_train_df, y_train_binary, variance_top_n=5000, k_final=1000):
    """Same two-stage approach, but ANOVA F-test computed on the binary NR-vs-Rejection labels."""
    gene_variances = gene_train_df.var(axis=0)
    top_variance_genes = gene_variances.nlargest(variance_top_n).index

    X_stage1 = gene_train_df[top_variance_genes]
    f_scores, p_values = f_classif(X_stage1, y_train_binary)

    f_score_series = pd.Series(f_scores, index=top_variance_genes)
    return f_score_series.nlargest(k_final).index.tolist()


rejection_focused_results = []

for fold in range(5):
    gene_train = fold_data[fold]['gene_train']
    gene_val = fold_data[fold]['gene_val']
    y_train = fold_data[fold]['y_train']
    y_val = fold_data[fold]['y_val']

    y_train_bin = to_binary_rejection(y_train)
    y_val_bin = to_binary_rejection(y_val)

    # select genes using the BINARY labels this time
    rejection_genes = select_genes_binary_focused(gene_train, y_train_bin, variance_top_n=5000, k_final=1000)

    X_train_k = gene_train[rejection_genes]
    X_val_k = gene_val[rejection_genes]

    clf = RandomForestClassifier(n_estimators=200, class_weight='balanced', random_state=42, n_jobs=-1)
    clf.fit(X_train_k, y_train_bin)
    preds = clf.predict(X_val_k)

    rec = recall_score(y_val_bin, preds, pos_label='Rejection')
    prec = precision_score(y_val_bin, preds, pos_label='Rejection')
    rejection_focused_results.append({'fold': fold, 'recall': rec, 'precision': prec})
    print(f"Fold {fold}: Rejection recall={rec:.3f}, precision={prec:.3f}")

rf_df = pd.DataFrame(rejection_focused_results)
print(f"\nMean rejection recall (rejection-focused genes): {rf_df['recall'].mean():.3f}")
print(f"Mean rejection precision (rejection-focused genes): {rf_df['precision'].mean():.3f}")
print(f"\nCompare to 4-class-selected genes: recall=0.815, precision=0.862")