# -*- coding: utf-8 -*-
"""data_preprocessing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oUKWBknEdmtx8Afa1H-Kf4ubfrKltpKl
"""

# ============================================================
# CELL 1 — Basic setup
# ============================================================

options(stringsAsFactors = FALSE)

repo_url <- "https://github.com/ErasmusMC-Bioinformatics/KidneyRejectionClassifier.git"
repo_dir <- "/content/KidneyRejectionClassifier"

if (!dir.exists(repo_dir)) {
  system2("git", c("clone", repo_url, repo_dir))
}

setwd(repo_dir)
dir.create("Data", showWarnings = FALSE, recursive = TRUE)

cat("Working directory:", getwd(), "\n")
cat("R version:", R.version.string, "\n")

# ============================================================
# CELL 2 — Install/load packages
# ============================================================
# IMPORTANT:
# The authors' original script contains:
#     library(quantable)
#
# quantable is no longer available for this modern R environment.
# We therefore DO NOT install it. Instead, below we reproduce the
# robustscale implementation used by quantable.

if (!requireNamespace("BiocManager", quietly = TRUE)) {
  install.packages("BiocManager", repos = "https://cloud.r-project.org")
}

cran_pkgs <- c("tidyverse", "ggplot2")
for (p in cran_pkgs) {
  if (!requireNamespace(p, quietly = TRUE)) {
    install.packages(p, repos = "https://cloud.r-project.org")
  }
}

if (!requireNamespace("GEOquery", quietly = TRUE)) {
  BiocManager::install("GEOquery", ask = FALSE, update = FALSE)
}

if (!requireNamespace("sva", quietly = TRUE)) {
  BiocManager::install("sva", ask = FALSE, update = FALSE)
}

library(GEOquery)
library(tidyverse)
library(ggplot2)
library(sva)

cat("Packages loaded successfully.\n")

# ============================================================
# CELL 3 — Compatibility implementation of quantable::robustscale
# ============================================================

# This is a local compatibility implementation of the quantable
# robustscale behavior needed by preprocessing.R.
#
# Defaults are retained:
#   dim = 2
#   center = TRUE
#   scale = FALSE
#   preserveScale = TRUE
#
# The authors call robustscale(dataset, dim = 1), so rows/features
# are centered using their row medians.

robustscale <- function(data, dim = 2, center = TRUE, scale = FALSE,
                        preserveScale = TRUE) {

  data <- as.matrix(data)

  if (!dim %in% c(1, 2)) {
    stop("dim must be 1 or 2")
  }

  medians <- NULL

  if (center) {
    if (dim == 1) {
      medians <- apply(data, 1, median, na.rm = TRUE)
      data <- sweep(data, 1, medians, "-")
    } else {
      medians <- apply(data, 2, median, na.rm = TRUE)
      data <- sweep(data, 2, medians, "-")
    }
  }

  mads <- NULL

  if (scale) {
    if (dim == 1) {
      mads <- apply(data, 1, mad, na.rm = TRUE)
      if (preserveScale) {
        mads <- mads / mean(mads, na.rm = TRUE)
      }
      data <- sweep(data, 1, mads, "/")
    } else {
      mads <- apply(data, 2, mad, na.rm = TRUE)
      if (preserveScale) {
        mads <- mads / mean(mads, na.rm = TRUE)
      }
      data <- sweep(data, 2, mads, "/")
    }
  }

  list(
    data = data,
    medians = medians,
    mads = mads
  )
}

# Sanity check that the compatibility function exists.
stopifnot(is.function(robustscale))
cat("Local robustscale() compatibility function is ready.\n")

# ============================================================
# CELL 4 — Download GEO series-matrix files
# ============================================================

download_if_missing <- function(url, dest) {
  if (!file.exists(dest)) {
    message("Downloading: ", url)
    download.file(url, destfile = dest, mode = "wb", quiet = FALSE)
  }
  if (!file.exists(dest)) {
    stop("Download failed: ", dest)
  }
}

geo1 <- "https://ftp.ncbi.nlm.nih.gov/geo/series/GSE98nnn/GSE98320/matrix/GSE98320_series_matrix.txt.gz"
geo2 <- "https://ftp.ncbi.nlm.nih.gov/geo/series/GSE129nnn/GSE129166/matrix/GSE129166_series_matrix.txt.gz"

download_if_missing(geo1, "Data/GSE98320_series_matrix.txt.gz")
download_if_missing(geo2, "Data/GSE129166_series_matrix.txt.gz")

# The authors' script expects uncompressed .txt files.
gunzip_if_needed <- function(gzfile, txtfile) {
  if (!file.exists(txtfile)) {
    con_in <- gzfile(gzfile, "rb")
    con_out <- file(txtfile, "wb")
    repeat {
      buf <- readBin(con_in, what = "raw", n = 1024^2)
      if (length(buf) == 0) break
      writeBin(buf, con_out)
    }
    close(con_in)
    close(con_out)
  }
  stopifnot(file.exists(txtfile))
}

gunzip_if_needed("Data/GSE98320_series_matrix.txt.gz",
                 "Data/GSE98320_series_matrix.txt")

gunzip_if_needed("Data/GSE129166_series_matrix.txt.gz",
                 "Data/GSE129166_series_matrix.txt")

cat("GEO series-matrix files are ready.\n")

# ============================================================
# CELL 5 — Install / verify the exact Affymetrix NA36 annotation files
# ============================================================

repo_dir <- "/content/KidneyRejectionClassifier"
data_dir <- file.path(repo_dir, "Data")

dir.create(data_dir, recursive = TRUE, showWarnings = FALSE)

primeview_file <- file.path(
  data_dir,
  "PrimeView.na36.annot.csv"
)

u133_file <- file.path(
  data_dir,
  "HG-U133_Plus_2.na36.annot.csv"
)

cat("\n")
cat("======================================================================\n")
cat("AFFYMETRIX NA36 ANNOTATION FILES\n")
cat("======================================================================\n")


# ------------------------------------------------------------
# 1. Check PrimeView annotation
# ------------------------------------------------------------

cat("\n[1/2] PrimeView.na36.annot.csv\n")

if (file.exists(primeview_file) &&
    file.info(primeview_file)$size > 1000) {

  cat("✓ Already exists\n")
  cat("  ", primeview_file, "\n", sep = "")

} else {

  stop(
    "PrimeView.na36.annot.csv is missing from:\n",
    data_dir
  )
}


# ------------------------------------------------------------
# 2. Check U133 Plus 2 annotation
# ------------------------------------------------------------

cat("\n[2/2] HG-U133_Plus_2.na36.annot.csv\n")

if (file.exists(u133_file) &&
    file.info(u133_file)$size > 1000) {

  cat("✓ Already exists\n")
  cat("  ", u133_file, "\n", sep = "")

} else {

  # Look for the ZIP uploaded to the normal Colab /content area.
  zip_candidates <- c(
    "/content/TFS-Assets_LSG_Support-Files_HG-U133_Plus_2-na36-annot-csv.zip",
    "/content/HG-U133_Plus_2-na36-annot-csv.zip",
    "/content/HG-U133_Plus_2.na36.annot.csv.zip"
  )

  zip_candidates <- zip_candidates[file.exists(zip_candidates)]

  if (length(zip_candidates) == 0) {

    stop(
      "\nHG-U133_Plus_2.na36.annot.csv was not found.\n\n",
      "Please upload the ZIP file through the Colab Files panel.\n",
      "It should appear under /content/.\n\n",
      "Expected file:\n",
      "TFS-Assets_LSG_Support-Files_HG-U133_Plus_2-na36-annot-csv.zip\n"
    )
  }

  u133_zip <- zip_candidates[1]

  cat("✓ ZIP found:\n")
  cat("  ", u133_zip, "\n", sep = "")

  cat("\nExtracting...\n")

  # Extract into a temporary directory first
  extract_dir <- file.path(
    tempdir(),
    "HG_U133_NA36"
  )

  dir.create(
    extract_dir,
    recursive = TRUE,
    showWarnings = FALSE
  )

  unzip(
    u133_zip,
    exdir = extract_dir
  )

  # Find the exact CSV inside the extracted files
  extracted_csv <- list.files(
    extract_dir,
    pattern = "^HG-U133_Plus_2\\.na36\\.annot\\.csv$",
    recursive = TRUE,
    full.names = TRUE
  )

  if (length(extracted_csv) == 0) {

    stop(
      "\nThe ZIP was found, but HG-U133_Plus_2.na36.annot.csv\n",
      "was not found inside it.\n\n",
      "Files extracted were:\n",
      paste(
        list.files(
          extract_dir,
          recursive = TRUE,
          full.names = FALSE
        ),
        collapse = "\n"
      )
    )
  }

  # Copy the exact annotation file into the repository Data folder
  file.copy(
    from = extracted_csv[1],
    to = u133_file,
    overwrite = TRUE
  )

  cat("\n✓ HG-U133_Plus_2.na36.annot.csv extracted successfully\n")
  cat("  ", u133_file, "\n", sep = "")
}


# ------------------------------------------------------------
# 3. Final verification
# ------------------------------------------------------------

cat("\n")
cat("======================================================================\n")
cat("FINAL VERIFICATION\n")
cat("======================================================================\n")

if (!file.exists(primeview_file)) {
  stop("PrimeView annotation verification failed.")
}

if (!file.exists(u133_file)) {
  stop("HG-U133_Plus_2 annotation verification failed.")
}

primeview_size <- file.info(primeview_file)$size
u133_size <- file.info(u133_file)$size

cat("\n✓ PrimeView.na36.annot.csv\n")
cat("  Size:", primeview_size, "bytes\n")

cat("\n✓ HG-U133_Plus_2.na36.annot.csv\n")
cat("  Size:", u133_size, "bytes\n")

cat("\n")
cat("======================================================================\n")
cat("PASS — BOTH NA36 ANNOTATION FILES ARE READY\n")
cat("======================================================================\n")

# ============================================================
# CELL 6 — Functions from authors' preprocessing.R
# ============================================================

library(GEOquery)
library(tidyverse)
library(ggplot2)
library(sva)

# ------------------------------------------------------------
# 1. Load expression data
# ------------------------------------------------------------

loadExpressionData <- function(filename) {

  start_pattern <- "!series_matrix_table_begin"
  end_pattern   <- "!series_matrix_table_end"

  GEO_lines <- readLines(filename, warn = FALSE)

  GEO_start <- grep(start_pattern, GEO_lines)
  GEO_end   <- grep(end_pattern, GEO_lines)

  if (length(GEO_start) != 1) {
    stop("Could not uniquely locate !series_matrix_table_begin")
  }

  if (length(GEO_end) != 1) {
    stop("Could not uniquely locate !series_matrix_table_end")
  }

  GEO_nrows <- GEO_end - GEO_start - 2

  GEO <- read.table(
    filename,
    header = TRUE,
    sep = "",
    skip = GEO_start,
    nrows = GEO_nrows,
    quote = "\"",
    comment.char = "",
    check.names = TRUE,
    stringsAsFactors = FALSE
  )

  GEO$ID_REF <- gsub('"', '', GEO$ID_REF)

  return(GEO)
}


# ------------------------------------------------------------
# 2. Load GEO sample metadata
#
# This follows the authors' intended structure:
#   - sample metadata are read from !Sample_title
#     through the line before !series_matrix_table_begin
#   - first field = metadata variable name
#   - remaining fields = sample values
#   - transpose so samples are rows
#
# The explicit parsing avoids the zero-row problem encountered
# with the original nrows-based implementation on GSE98320.
# ------------------------------------------------------------

loadMetaData <- function(filename) {

  GEO_lines <- readLines(filename, warn = FALSE)

  # Locate metadata block
  start_pattern <- "^!Sample_title"
  end_pattern   <- "^!series_matrix_table_begin"

  meta_start <- grep(start_pattern, GEO_lines)
  meta_end   <- grep(end_pattern, GEO_lines)

  if (length(meta_start) != 1) {
    stop(
      paste0(
        "Could not uniquely locate !Sample_title. ",
        "Found ", length(meta_start), " matches."
      )
    )
  }

  if (length(meta_end) != 1) {
    stop(
      paste0(
        "Could not uniquely locate !series_matrix_table_begin. ",
        "Found ", length(meta_end), " matches."
      )
    )
  }

  if (meta_end <= meta_start) {
    stop("Metadata block boundaries are invalid.")
  }

  # Extract all !Sample_* lines
  meta_lines <- GEO_lines[meta_start:(meta_end - 1)]

  if (length(meta_lines) == 0) {
    stop("No GEO sample metadata lines were found.")
  }

  # ----------------------------------------------------------
  # Parse GEO metadata.
  #
  # sep="" is intentional:
  # GEO values are quoted, so spaces inside quoted values are
  # preserved while whitespace separates fields.
  # ----------------------------------------------------------

  meta_df <- read.table(
    text = meta_lines,
    header = FALSE,
    sep = "",
    quote = "\"",
    fill = TRUE,
    comment.char = "",
    check.names = FALSE,
    stringsAsFactors = FALSE
  )

  if (nrow(meta_df) == 0 || ncol(meta_df) < 2) {
    stop(
      paste0(
        "Metadata parsing failed: ",
        nrow(meta_df), " rows x ",
        ncol(meta_df), " columns."
      )
    )
  }

  # ----------------------------------------------------------
  # First column = metadata field names
  # Remaining columns = samples
  # ----------------------------------------------------------

  field_names <- meta_df[[1]]

  values <- meta_df[, -1, drop = FALSE]

  # Make field names syntactically valid and unique,
  # matching the behavior of the authors' code.
  field_names <- make.names(
    field_names,
    unique = TRUE
  )

  rownames(values) <- field_names

  # ----------------------------------------------------------
  # Transpose:
  #
  # before:
  #   metadata fields x samples
  #
  # after:
  #   samples x metadata fields
  # ----------------------------------------------------------

  meta_df <- as.data.frame(
    t(values),
    stringsAsFactors = FALSE,
    check.names = TRUE
  )

  # ----------------------------------------------------------
  # Confirm sample accession field exists
  # ----------------------------------------------------------

  if (!"X.Sample_geo_accession" %in% colnames(meta_df)) {

    cat("\nERROR: X.Sample_geo_accession was not found.\n\n")

    cat("Parsed metadata columns:\n")
    print(colnames(meta_df))

    cat("\nFirst metadata field names:\n")
    print(head(field_names, 20))

    stop("X.Sample_geo_accession was not found.")
  }

  # ----------------------------------------------------------
  # Use GEO accession as row names
  # This reproduces the authors' original behavior:
  #
  # rownames(meta_df) =
  #     make.names(meta_df$X.Sample_geo_accession, unique=TRUE)
  # ----------------------------------------------------------

  rownames(meta_df) <- make.names(
    meta_df$X.Sample_geo_accession,
    unique = TRUE
  )

  return(meta_df)
}


# ------------------------------------------------------------
# 3. Probe -> gene mapping and median aggregation
# ------------------------------------------------------------

matchAggregate <- function(expression, mapping, id_type) {

  expression$Probe.Set.ID <- expression$ID_REF

  expression_mapped <- left_join(
    expression,
    mapping,
    by = "Probe.Set.ID"
  )

  expression_aggre <- aggregate(
    subset(
      expression_mapped,
      select = -c(ID_REF, Probe.Set.ID)
    ),
    by = list(expression_mapped[[id_type]]),
    FUN = function(x) median(x)
  )

  names(expression_aggre)[
    names(expression_aggre) == "Group.1"
  ] <- id_type

  return(expression_aggre)
}


# ------------------------------------------------------------
# 4. Load probe annotation mapping
# ------------------------------------------------------------

getProbeMapping <- function(
  probe_annotation_file,
  identifier_type
) {

  probe_annot <- read.table(
    probe_annotation_file,
    header = TRUE,
    sep = ",",
    skip = 25,
    quote = "\"",
    comment.char = "",
    check.names = FALSE,
    stringsAsFactors = FALSE
  )

  probe_mapping <- probe_annot[
    ,
    c("Probe.Set.ID", identifier_type)
  ]

  probe_mapping <- separate_rows(
    probe_mapping,
    identifier_type,
    sep = " /// "
  )

  return(probe_mapping)
}


# ------------------------------------------------------------
# 5. Combine datasets using shared Entrez genes
# ------------------------------------------------------------

combineDataSets <- function(dataset1, dataset2) {

  shared.genes <- intersect(
    dataset1[["Entrez.Gene"]],
    dataset2[["Entrez.Gene"]]
  )

  dataset1 <- dataset1[
    dataset1[["Entrez.Gene"]] %in% shared.genes,
    ,
    drop = FALSE
  ]

  dataset2 <- dataset2[
    dataset2[["Entrez.Gene"]] %in% shared.genes,
    ,
    drop = FALSE
  ]

  rownames(dataset1) <- dataset1[["Entrez.Gene"]]
  rownames(dataset2) <- dataset2[["Entrez.Gene"]]

  combined.dataset <- cbind(
    dataset1,
    dataset2
  )

  combined.dataset <- combined.dataset[
    ,
    -which(
      names(combined.dataset) %in%
        c(
          "X",
          "Entrez.Gene",
          "ID_REF",
          "Probe.Set.ID"
        )
    ),
    drop = FALSE
  ]

  return(combined.dataset)
}


# ------------------------------------------------------------
# 6. ComBat + robust scaling
#
# quantable::robustscale() is not installed here, so the
# compatibility implementation below reproduces the behavior
# required by the authors' call:
#
#   robustscale(dataset, dim = 1)$data
#
# with center = TRUE and scale = FALSE.
# ------------------------------------------------------------

robustscale <- function(
  data,
  dim = 2,
  center = TRUE,
  scale = FALSE,
  preserveScale = TRUE
) {

  data <- as.matrix(data)

  if (dim == 1) {

    # Scale each column using its median
    if (center) {
      centers <- apply(
        data,
        2,
        median,
        na.rm = TRUE
      )

      data <- sweep(
        data,
        2,
        centers,
        FUN = "-"
      )
    }

    if (scale) {

      scales <- apply(
        data,
        2,
        function(x) {
          mad(
            x,
            center = 0,
            constant = 1,
            na.rm = TRUE
          )
        }
      )

      scales[scales == 0 | is.na(scales)] <- 1

      data <- sweep(
        data,
        2,
        scales,
        FUN = "/"
      )
    }

  } else {

    # Scale each row
    if (center) {
      centers <- apply(
        data,
        1,
        median,
        na.rm = TRUE
      )

      data <- sweep(
        data,
        1,
        centers,
        FUN = "-"
      )
    }

    if (scale) {

      scales <- apply(
        data,
        1,
        function(x) {
          mad(
            x,
            center = 0,
            constant = 1,
            na.rm = TRUE
          )
        }
      )

      scales[scales == 0 | is.na(scales)] <- 1

      data <- sweep(
        data,
        1,
        scales,
        FUN = "/"
      )
    }
  }

  return(
    list(
      data = data
    )
  )
}


# ------------------------------------------------------------
# 7. ComBat + robust scaling of each dataset separately
# ------------------------------------------------------------

normalizeScaleDatasets <- function(
  combined.dataset,
  batch.indication
) {

  combat.combined <- ComBat(
    dat = combined.dataset,
    batch = batch.indication,
    mod = NULL,
    par.prior = TRUE,
    prior.plots = FALSE
  )

  dataset.names <- unique(batch.indication)

  n.datasets <- length(dataset.names)

  datasets <- list()

  for (i in seq_len(n.datasets)) {

    dataset <- combat.combined[
      ,
      which(
        batch.indication == dataset.names[[i]]
      ),
      drop = FALSE
    ]

    dataset.scaled <- robustscale(
      dataset,
      dim = 1
    )$data

    datasets[[i]] <- dataset.scaled
  }

  return(datasets)
}


# ------------------------------------------------------------
# Cell 6 sanity check
# ------------------------------------------------------------

cat("Cell 6 loaded successfully.\n")
cat("Functions available:\n")
cat("  loadExpressionData()\n")
cat("  loadMetaData()\n")
cat("  matchAggregate()\n")
cat("  getProbeMapping()\n")
cat("  combineDataSets()\n")
cat("  robustscale()\n")
cat("  normalizeScaleDatasets()\n")

# ============================================================
# CELL 7 — LOAD ANNOTATION MAPPINGS — CORRECTED
# ============================================================

cat("============================================\n")
cat("CELL 7 — LOAD ANNOTATION MAPPINGS\n")
cat("============================================\n\n")

primeview_file <- "Data/PrimeView.na36.annot.csv"
hgu133plus2_file <- "Data/HG-U133_Plus_2.na36.annot.csv"

stopifnot(file.exists(primeview_file))
stopifnot(file.exists(hgu133plus2_file))


# ------------------------------------------------------------
# 1. Load PrimeView
# ------------------------------------------------------------

primeview_annot <- read.csv(
  primeview_file,
  header = TRUE,
  stringsAsFactors = FALSE,
  check.names = FALSE
)

cat("PrimeView annotation dimensions:\n")
print(dim(primeview_annot))

cat("\nPrimeView columns:\n")
print(names(primeview_annot))


# ------------------------------------------------------------
# 2. Load historical HG-U133 Plus 2 NA36
# ------------------------------------------------------------
# The actual header is line 26, hence skip = 25.

hgu133plus2_annot <- read.csv(
  hgu133plus2_file,
  header = TRUE,
  skip = 25,
  stringsAsFactors = FALSE,
  check.names = FALSE
)

cat("\nHG-U133 Plus 2 annotation dimensions:\n")
print(dim(hgu133plus2_annot))


# ------------------------------------------------------------
# 3. Create PrimeView mapping
# ------------------------------------------------------------
# PrimeView uses "ID" for the probe identifier.

stopifnot("ID" %in% names(primeview_annot))
stopifnot("Entrez Gene" %in% names(primeview_annot))

primeview_entrez_mapping <- primeview_annot[, c(
  "ID",
  "Entrez Gene"
)]

names(primeview_entrez_mapping) <- c(
  "Probe.Set.ID",
  "Entrez.Gene"
)


# ------------------------------------------------------------
# 4. Create HG-U133 Plus 2 mapping
# ------------------------------------------------------------

stopifnot("Probe Set ID" %in% names(hgu133plus2_annot))
stopifnot("Entrez Gene" %in% names(hgu133plus2_annot))

hgu133plus2_entrez_mapping <- hgu133plus2_annot[, c(
  "Probe Set ID",
  "Entrez Gene"
)]

names(hgu133plus2_entrez_mapping) <- c(
  "Probe.Set.ID",
  "Entrez.Gene"
)


# ------------------------------------------------------------
# 5. Reproduce authors' separate_rows() behavior
# ------------------------------------------------------------

primeview_entrez_mapping <- primeview_entrez_mapping %>%
  tidyr::separate_rows(
    Entrez.Gene,
    sep = " /// "
  )

hgu133plus2_entrez_mapping <- hgu133plus2_entrez_mapping %>%
  tidyr::separate_rows(
    Entrez.Gene,
    sep = " /// "
  )


# ------------------------------------------------------------
# 6. Convert empty mappings to NA
# ------------------------------------------------------------

primeview_entrez_mapping$Entrez.Gene[
  trimws(primeview_entrez_mapping$Entrez.Gene) == ""
] <- NA

hgu133plus2_entrez_mapping$Entrez.Gene[
  trimws(hgu133plus2_entrez_mapping$Entrez.Gene) == ""
] <- NA


# ------------------------------------------------------------
# 7. Final verification
# ------------------------------------------------------------

cat("\n============================================\n")
cat("MAPPING OBJECT CHECK\n")
cat("============================================\n\n")

cat(
  "primeview_entrez_mapping exists:",
  exists("primeview_entrez_mapping"),
  "\n"
)

cat(
  "hgu133plus2_entrez_mapping exists:",
  exists("hgu133plus2_entrez_mapping"),
  "\n\n"
)

cat("PrimeView mapping dimensions:\n")
print(dim(primeview_entrez_mapping))

cat("\nHG-U133 Plus 2 mapping dimensions:\n")
print(dim(hgu133plus2_entrez_mapping))

cat("\nPrimeView mapping preview:\n")
print(head(primeview_entrez_mapping))

cat("\nHG-U133 Plus 2 mapping preview:\n")
print(head(hgu133plus2_entrez_mapping))

cat("\n============================================\n")
cat("✓ CELL 7 COMPLETED SUCCESSFULLY\n")
cat("============================================\n")

# ============================================================
# CELL 8 — Load expression and metadata
# ============================================================

GSE98320 <- loadExpressionData(
  "Data/GSE98320_series_matrix.txt"
)

GSE129166 <- loadExpressionData(
  "Data/GSE129166_series_matrix.txt"
)

GSE98320_meta <- loadMetaData(
  "Data/GSE98320_series_matrix.txt"
)

GSE129166_meta <- loadMetaData(
  "Data/GSE129166_series_matrix.txt"
)

cat("GSE98320 expression:", nrow(GSE98320), "probes x",
    ncol(GSE98320) - 1, "samples\n")

cat("GSE129166 expression:", nrow(GSE129166), "probes x",
    ncol(GSE129166) - 1, "samples\n")

cat("GSE98320 metadata dimensions:\n")
print(dim(GSE98320_meta))

cat("\nFirst metadata columns:\n")
print(colnames(GSE98320_meta)[1:10])

cat("\nSample accession examples:\n")
print(head(GSE98320_meta$X.Sample_geo_accession))

cat("\nCluster values:\n")
print(table(GSE98320_meta$X.Sample_characteristics_ch1.1, useNA = "ifany"))

# ============================================================
# CELL 9 — Reproduce the authors' sample labels exactly
#         SELF-CONTAINED VERSION
# ============================================================

cat("============================================\n")
cat("CELL 9 — AUTHOR LABELING\n")
cat("============================================\n")


# ------------------------------------------------------------
# SAFETY CHECK
# ------------------------------------------------------------
# Cell 8 should have created GSE98320_meta with 1208 rows.
# If it is empty/stale, reload it using loadMetaData().
# ------------------------------------------------------------

if (
  !exists("GSE98320_meta") ||
  nrow(GSE98320_meta) == 0
) {

  cat("\nGSE98320_meta is empty or does not exist.\n")
  cat("Reloading GSE98320 metadata...\n\n")

  GSE98320_meta <- loadMetaData(
    GSE98320_file
  )
}


if (
  !exists("GSE129166_meta") ||
  nrow(GSE129166_meta) == 0
) {

  cat("\nGSE129166_meta is empty or does not exist.\n")
  cat("Reloading GSE129166 metadata...\n\n")

  GSE129166_meta <- loadMetaData(
    GSE129166_file
  )
}


# ------------------------------------------------------------
# CHECK METADATA BEFORE LABELING
# ------------------------------------------------------------

cat("GSE98320 metadata dimensions:\n")
print(dim(GSE98320_meta))

cat("\nGSE129166 metadata dimensions:\n")
print(dim(GSE129166_meta))


# ------------------------------------------------------------
# IMPORTANT:
# Your GSE98320 metadata uses:
#
#   "archetype cluster: 1"
#   "archetype cluster: 2"
#   ...
#
# rather than the wording used in the paper/repository code.
#
# We therefore use the actual values in this GEO file while
# preserving the authors' cluster -> diagnosis mapping:
#
#   cluster 1 -> NR
#   cluster 2 -> TCMR
#   cluster 3 -> excluded
#   cluster 4 -> ABMR
#   cluster 5 -> ABMR
#   cluster 6 -> ABMR
# ------------------------------------------------------------


# Identify the actual cluster field
cluster_column <- "X.Sample_characteristics_ch1.1"

if (!cluster_column %in% colnames(GSE98320_meta)) {

  cat("\nAvailable GSE98320 metadata columns:\n")
  print(colnames(GSE98320_meta))

  stop(
    paste0(
      "Required cluster column not found: ",
      cluster_column
    )
  )
}


# ------------------------------------------------------------
# Inspect cluster values
# ------------------------------------------------------------

cat("\nGSE98320 cluster distribution BEFORE labeling:\n")

print(
  table(
    GSE98320_meta[[cluster_column]],
    useNA = "ifany"
  )
)


# ------------------------------------------------------------
# AUTHOR CLUSTER -> DIAGNOSIS MAPPING
# ------------------------------------------------------------

GSE98320_meta$Label <- with(
  GSE98320_meta,

  ifelse(
    X.Sample_characteristics_ch1.1 ==
      "archetype cluster: 1",

    "NR",

    ifelse(
      X.Sample_characteristics_ch1.1 ==
        "archetype cluster: 4" |

      X.Sample_characteristics_ch1.1 ==
        "archetype cluster: 5" |

      X.Sample_characteristics_ch1.1 ==
        "archetype cluster: 6",

      "ABMR",

      ifelse(
        X.Sample_characteristics_ch1.1 ==
          "archetype cluster: 2",

        "TCMR",

        ""
      )
    )
  )
)


# ------------------------------------------------------------
# CHECK LABELS BEFORE FILTERING
# ------------------------------------------------------------

cat("\nGSE98320 labels BEFORE filtering:\n")

print(
  table(
    GSE98320_meta$Label,
    useNA = "ifany"
  )
)


cat("\nGSE98320 samples BEFORE filtering:\n")
print(nrow(GSE98320_meta))


# ------------------------------------------------------------
# Remove cluster 3 / unclassified samples
# ------------------------------------------------------------

GSE98320_meta <- GSE98320_meta[
  GSE98320_meta$Label %in%
    c("NR", "ABMR", "TCMR"),
  ,
  drop = FALSE
]


# ------------------------------------------------------------
# GSE98320 FINAL CHECK
# ------------------------------------------------------------

cat("\nGSE98320 samples AFTER filtering:\n")
print(nrow(GSE98320_meta))

cat("\nGSE98320 FINAL CLASS DISTRIBUTION:\n")

print(
  table(
    GSE98320_meta$Label
  )
)


# ============================================================
# GSE129166
# ============================================================

# ------------------------------------------------------------
# Keep only kidney allograft biopsy samples
# ------------------------------------------------------------

GSE129166_meta <- GSE129166_meta[
  GSE129166_meta$X.Sample_characteristics_ch1 ==
    "tissue: kidney allograft biopsy",
  ,
  drop = FALSE
]


# ------------------------------------------------------------
# Authors' GSE129166 labeling
# ------------------------------------------------------------

GSE129166_meta$Label <- with(
  GSE129166_meta,

  ifelse(

    X.Sample_characteristics_ch1.1 ==
      "tcmr (no: 0_borderline:1_TCMR:2): 0" &

    X.Sample_characteristics_ch1.2 ==
      "abmr (no: 0_Yes:1): 0",

    "NR",

    ifelse(

      X.Sample_characteristics_ch1.1 ==
        "tcmr (no: 0_borderline:1_TCMR:2): 0" &

      X.Sample_characteristics_ch1.2 ==
        "abmr (no: 0_Yes:1): 1",

      "ABMR",

      ifelse(

        X.Sample_characteristics_ch1.1 ==
          "tcmr (no: 0_borderline:1_TCMR:2): 2" &

        X.Sample_characteristics_ch1.2 ==
          "abmr (no: 0_Yes:1): 0",

        "TCMR",

        ""
      )
    )
  )
)


# ------------------------------------------------------------
# Keep only valid diagnostic classes
# ------------------------------------------------------------

GSE129166_meta <- GSE129166_meta[
  GSE129166_meta$Label %in%
    c("NR", "ABMR", "TCMR"),
  ,
  drop = FALSE
]


# ============================================================
# FINAL OUTPUT
# ============================================================

cat("\n============================================\n")
cat("FINAL LABEL CHECK\n")
cat("============================================\n")


cat("\nGSE98320:\n")
cat(
  "Samples retained:",
  nrow(GSE98320_meta),
  "\n"
)

print(
  table(
    GSE98320_meta$Label
  )
)


cat("\nGSE129166:\n")
cat(
  "Samples retained:",
  nrow(GSE129166_meta),
  "\n"
)

print(
  table(
    GSE129166_meta$Label
  )
)


# ============================================================
# HARD REPRODUCTION CHECKS
# ============================================================

# Training cohort
stopifnot(
  nrow(GSE98320_meta) == 1181
)

stopifnot(
  identical(
    as.integer(
      table(GSE98320_meta$Label)[
        c("NR", "ABMR", "TCMR")
      ]
    ),
    c(774L, 326L, 81L)
  )
)


# External validation cohort
stopifnot(
  nrow(GSE129166_meta) == 77
)

stopifnot(
  identical(
    as.integer(
      table(GSE129166_meta$Label)[
        c("NR", "ABMR", "TCMR")
      ]
    ),
    c(60L, 15L, 2L)
  )
)


cat("\n============================================\n")
cat("✓ CELL 9 COMPLETED SUCCESSFULLY\n")
cat("============================================\n")

cat("GSE98320: 1181 samples\n")
cat("  NR   =", 774, "\n")
cat("  ABMR =", 326, "\n")
cat("  TCMR =", 81, "\n")

cat("\nGSE129166: 77 samples\n")
cat("  NR   =", 60, "\n")
cat("  ABMR =", 15, "\n")
cat("  TCMR =", 2, "\n")

# ============================================================
# CELL 10 — Save phenotype files exactly as authors do
# ============================================================

GSE98320_pheno <- data.frame(
  Sample_id = rownames(GSE98320_meta),
  Label = GSE98320_meta$Label
)

GSE129166_pheno <- data.frame(
  Sample_id = rownames(GSE129166_meta),
  Label = GSE129166_meta$Label
)

write.table(
  GSE98320_pheno,
  file = "Data/GSE98320.phenotype.csv",
  row.names = FALSE,
  col.names = TRUE,
  quote = FALSE,
  sep = ","
)

write.table(
  GSE129166_pheno,
  file = "Data/GSE129166.phenotype.csv",
  row.names = FALSE,
  col.names = TRUE,
  quote = FALSE,
  sep = ","
)

cat("Phenotype files written.\n")

# ============================================================
# CELL 11 — Filter expression to the selected phenotypes
# ============================================================

GSE129166_biopsies <- GSE129166[
  ,
  colnames(GSE129166) %in%
    c(GSE129166_pheno$Sample_id, "ID_REF")
]

GSE98320 <- GSE98320[
  ,
  colnames(GSE98320) %in%
    c(GSE98320_pheno$Sample_id, "ID_REF")
]

cat("Filtered GSE98320:", nrow(GSE98320), "probes x",
    ncol(GSE98320) - 1, "samples\n")

cat("Filtered GSE129166 biopsies:", nrow(GSE129166_biopsies),
    "probes x", ncol(GSE129166_biopsies) - 1, "samples\n")

cat("PrimeView mapping exists:", exists("primeview_entrez_mapping"), "\n")
cat("U133 mapping exists:", exists("u133_entrez_mapping"), "\n")

if (exists("primeview_entrez_mapping")) {
  cat("PrimeView mapping dimensions:", dim(primeview_entrez_mapping), "\n")
}

if (exists("u133_entrez_mapping")) {
  cat("U133 mapping dimensions:", dim(u133_entrez_mapping), "\n")
}

# ============================================================
# DIAGNOSTIC — Annotation files and mapping objects
# ============================================================

cat("Working directory:\n")
print(getwd())

cat("\nData directory exists:", dir.exists("Data"), "\n")

cat("\nAnnotation files:\n")
print(list.files(
  "Data",
  pattern = "annot\\.csv$",
  full.names = TRUE
))

cat("\nExpected files:\n")
cat(
  "PrimeView: ",
  file.exists("Data/PrimeView.na36.annot.csv"),
  "\n"
)

cat(
  "HG-U133 Plus 2: ",
  file.exists("Data/HG-U133_Plus_2.na36.annot.csv"),
  "\n"
)

cat("\nMapping objects:\n")
cat(
  "primeview_entrez_mapping: ",
  exists("primeview_entrez_mapping"),
  "\n"
)

cat(
  "hgu133plus2_entrez_mapping: ",
  exists("hgu133plus2_entrez_mapping"),
  "\n"
)

# ============================================================
# CELL 12 — Probe -> Entrez mapping and median aggregation
# ============================================================

GSE98320_aggre <- matchAggregate(
  GSE98320,
  primeview_entrez_mapping,
  "Entrez.Gene"
)

GSE129166_biopsies_aggre <- matchAggregate(
  GSE129166_biopsies,
  hgu133plus2_entrez_mapping,
  "Entrez.Gene"
)

cat("Aggregated GSE98320 genes:", nrow(GSE98320_aggre), "\n")
cat("Aggregated GSE129166 genes:", nrow(GSE129166_biopsies_aggre), "\n")

# ============================================================
# CELL 13 — Common genes and joint dataset construction
# ============================================================

GSE98320_GSE129166_biopsies <- combineDataSets(
  GSE98320_aggre,
  GSE129166_biopsies_aggre
)

cat("Common genes after probe mapping:",
    nrow(GSE98320_GSE129166_biopsies), "\n")

cat("Combined samples:",
    ncol(GSE98320_GSE129166_biopsies), "\n")

# ============================================================
# CELL 14 — ComBat + separate author robust scaling
# ============================================================

combat_batch <- rep(
  c("GSE98320", "GSE129166.biopsies"),
  times = c(
    nrow(GSE98320_pheno),
    nrow(GSE129166_pheno)
  )
)

datasets <- normalizeScaleDatasets(
  as.matrix(GSE98320_GSE129166_biopsies),
  combat_batch
)

combined_scaled_datasets <- as.data.frame(
  t(do.call(cbind, datasets))
)

cat("Scaled combined matrix:",
    nrow(combined_scaled_datasets), "samples x",
    ncol(combined_scaled_datasets), "genes\n")

# ============================================================
# CELL 15 — Separate datasets and save authors' output files
# ============================================================

combat_scaled_GSE98320 <-
  combined_scaled_datasets[
    GSE98320_pheno$Sample_id,
  ]

combat_scaled_GSE129166_biopsy <-
  combined_scaled_datasets[
    GSE129166_pheno$Sample_id,
  ]

write.table(
  combat_scaled_GSE98320,
  file = "Data/combat.scaled.GSE98320.csv",
  row.names = TRUE,
  col.names = TRUE,
  quote = FALSE,
  sep = ","
)

write.table(
  combat_scaled_GSE129166_biopsy,
  file = "Data/combat.scaled.GSE129166.biopsy.csv",
  row.names = TRUE,
  col.names = TRUE,
  quote = FALSE,
  sep = ","
)

cat("Author-style processed matrices written.\n")

# ============================================================
# CELL 16 — Verify processed matrices
# ============================================================

train_author <- read.csv(
  "Data/combat.scaled.GSE98320.csv",
  check.names = FALSE,
  row.names = 1
)

test_author <- read.csv(
  "Data/combat.scaled.GSE129166.biopsy.csv",
  check.names = FALSE,
  row.names = 1
)

cat("Training:", nrow(train_author), "samples x",
    ncol(train_author), "features\n")

cat("Validation:", nrow(test_author), "samples x",
    ncol(test_author), "features\n")

stopifnot(nrow(train_author) == 1181)
stopifnot(nrow(test_author) == 77)

# ============================================================
# CELL 17 — Load repository B-HOT+ mapping
# ============================================================

mapping_path <- "Data/BHOT_plus_entrez_mapping.csv"

if (!file.exists(mapping_path)) {
  stop("Missing repository mapping: ", mapping_path)
}

raw_map <- read.csv(
  mapping_path,
  header = FALSE,
  stringsAsFactors = FALSE,
  check.names = FALSE
)

parts <- strsplit(
  raw_map[[1]],
  ";",
  fixed = TRUE
)

bhot_map <- do.call(
  rbind,
  lapply(parts, function(x) {
    x <- c(x, rep("", max(0, 3 - length(x))))
    x[1:3]
  })
)

bhot_map <- as.data.frame(
  bhot_map,
  stringsAsFactors = FALSE
)

names(bhot_map) <- c(
  "original_name",
  "gene_symbol",
  "entrez_id"
)

bhot_map$entrez_id <- trimws(bhot_map$entrez_id)

bhot_ids <- unique(
  bhot_map$entrez_id[
    bhot_map$entrez_id != "" &
    bhot_map$entrez_id != "---"
  ]
)

cat("Unique mapped Entrez IDs:", length(bhot_ids), "\n")

# ============================================================
# CELL 18 — Match B-HOT+ features to processed matrices
# ============================================================

clean_id <- function(x) {
  x <- sub("^X", "", x)
  trimws(x)
}

train_names <- clean_id(colnames(train_author))
test_names <- clean_id(colnames(test_author))

bhot_train <- intersect(
  bhot_ids,
  train_names
)

bhot_test <- intersect(
  bhot_ids,
  test_names
)

common_bhot <- intersect(
  bhot_train,
  bhot_test
)

cat("B-HOT+ IDs in training matrix:", length(bhot_train), "\n")
cat("B-HOT+ IDs in validation matrix:", length(bhot_test), "\n")
cat("B-HOT+ IDs common to both:", length(common_bhot), "\n")

missing_train <- setdiff(bhot_ids, train_names)
missing_test <- setdiff(bhot_ids, test_names)

cat("\nB-HOT+ IDs missing from training matrix:\n")
print(missing_train)

cat("\nB-HOT+ IDs missing from validation matrix:\n")
print(missing_test)

# ============================================================
# CELL 19 — Strict B-HOT+ feature-count checkpoint
# ============================================================

if (length(common_bhot) != 768) {

  cat("\n============================================\n")
  cat("B-HOT+ REPRODUCTION DID NOT PASS\n")
  cat("============================================\n")
  cat("Expected common B-HOT+ features: 768\n")
  cat("Observed common B-HOT+ features: ", length(common_bhot), "\n\n", sep = "")

  cat("Missing from training:\n")
  print(missing_train)

  cat("\nMissing from validation:\n")
  print(missing_test)

  stop(
    "The exact 768-gene B-HOT+ feature space was not reproduced. ",
    "Do not pad or impute features."
  )
}

cat("PASS: 768 common B-HOT+ features reproduced.\n")

# ============================================================
# DIAGNOSTIC — INSPECT REPOSITORY B-HOT+ MAPPING
# ============================================================

mapping_path <- "Data/BHOT_plus_entrez_mapping.csv"

stopifnot(file.exists(mapping_path))

cat("Mapping file:\n", mapping_path, "\n\n")

# Read exactly as a normal semicolon-delimited CSV
map_test <- read.csv(
  mapping_path,
  header = TRUE,
  sep = ";",
  stringsAsFactors = FALSE,
  check.names = FALSE
)

cat("Dimensions:\n")
print(dim(map_test))

cat("\nColumn names:\n")
print(names(map_test))

cat("\nFirst 10 rows:\n")
print(head(map_test, 10))

cat("\nLast 10 rows:\n")
print(tail(map_test, 10))

cat("\nUnique Entrez IDs:\n")
print(length(unique(trimws(map_test[[3]]))))

cat("\nBlank Entrez IDs:\n")
print(sum(trimws(map_test[[3]]) == ""))

cat("\nLiteral NA Entrez IDs:\n")
print(sum(toupper(trimws(map_test[[3]])) == "NA"))

cat("\nLiteral --- Entrez IDs:\n")
print(sum(trimws(map_test[[3]]) == "---"))

# ============================================================
# DIAGNOSTIC — EXACT B-HOT+ ROWS VS PROCESSED GENE SPACE
# ============================================================

bhot_map <- map_test

# Clean Entrez IDs
bhot_map$`Entrez Gene` <- trimws(as.character(bhot_map$`Entrez Gene`))

# Remove genuinely empty/NA mappings
bhot_map_clean <- bhot_map[
  !is.na(bhot_map$`Entrez Gene`) &
  bhot_map$`Entrez Gene` != "" &
  toupper(bhot_map$`Entrez Gene`) != "NA",
]

cat("B-HOT+ mapping rows:", nrow(bhot_map_clean), "\n")
cat("Unique Entrez IDs:", length(unique(bhot_map_clean$`Entrez Gene`)), "\n\n")

# Duplicate Entrez IDs
dup_ids <- names(which(table(bhot_map_clean$`Entrez Gene`) > 1))

cat("Duplicated Entrez IDs:\n")
print(
  bhot_map_clean[
    bhot_map_clean$`Entrez Gene` %in% dup_ids,
    c("Original BHOT names", "Edited Gene Name", "Entrez Gene")
  ],
  row.names = FALSE
)

cat("\nNumber of duplicated Entrez IDs:", length(dup_ids), "\n\n")

# IDs present/absent in processed training matrix
processed_ids <- colnames(GSE98320_processed)

mapped_ids <- unique(bhot_map_clean$`Entrez Gene`)

present <- intersect(mapped_ids, processed_ids)
missing <- setdiff(mapped_ids, processed_ids)

cat("Mapped unique IDs:", length(mapped_ids), "\n")
cat("Present in processed matrix:", length(present), "\n")
cat("Missing from processed matrix:", length(missing), "\n\n")

cat("Missing IDs:\n")
print(missing)

cat("\nMissing genes with mapping names:\n")
print(
  bhot_map_clean[
    bhot_map_clean$`Entrez Gene` %in% missing,
    c("Original BHOT names", "Edited Gene Name", "Entrez Gene")
  ],
  row.names = FALSE
)

# ============================================================
# FIND THE ACTUAL PROCESSED MATRIX OBJECTS
# ============================================================

cat("Objects containing GSE98320:\n")
print(ls(pattern = "GSE98320"))

cat("\nObjects containing GSE129166:\n")
print(ls(pattern = "GSE129166"))

cat("\nObjects containing 'combat':\n")
print(ls(pattern = "combat", ignore.case = TRUE))

cat("\nObjects containing 'scaled':\n")
print(ls(pattern = "scaled", ignore.case = TRUE))

# ============================================================
# DEFINITIVE B-HOT+ FEATURE-SPACE DIAGNOSTIC
# ============================================================

# Use the actual author-preprocessed matrices
train_matrix <- combat_scaled_GSE98320
valid_matrix <- combat_scaled_GSE129166_biopsy

# Clean repository B-HOT+ mapping
bhot_map <- map_test

bhot_map$`Entrez Gene` <- trimws(as.character(bhot_map$`Entrez Gene`))

bhot_map_clean <- bhot_map[
  !is.na(bhot_map$`Entrez Gene`) &
  bhot_map$`Entrez Gene` != "" &
  toupper(bhot_map$`Entrez Gene`) != "NA",
]

bhot_ids <- unique(bhot_map_clean$`Entrez Gene`)

train_genes <- colnames(train_matrix)
valid_genes <- colnames(valid_matrix)

# Intersection
train_bhot <- intersect(bhot_ids, train_genes)
valid_bhot <- intersect(bhot_ids, valid_genes)
common_bhot <- intersect(train_bhot, valid_bhot)

cat("============================================\n")
cat("DEFINITIVE B-HOT+ FEATURE-SPACE CHECK\n")
cat("============================================\n\n")

cat("Author-preprocessed training matrix:\n")
cat("  samples =", nrow(train_matrix), "\n")
cat("  genes   =", ncol(train_matrix), "\n\n")

cat("Author-preprocessed validation matrix:\n")
cat("  samples =", nrow(valid_matrix), "\n")
cat("  genes   =", ncol(valid_matrix), "\n\n")

cat("Repository B-HOT+ mapping:\n")
cat("  valid mapping rows =", nrow(bhot_map_clean), "\n")
cat("  unique Entrez IDs  =", length(bhot_ids), "\n\n")

cat("B-HOT+ IDs present in training:\n")
cat(" ", length(train_bhot), "\n\n")

cat("B-HOT+ IDs present in validation:\n")
cat(" ", length(valid_bhot), "\n\n")

cat("B-HOT+ IDs common to both:\n")
cat(" ", length(common_bhot), "\n\n")

missing_train <- setdiff(bhot_ids, train_genes)
missing_valid <- setdiff(bhot_ids, valid_genes)

cat("Missing from training:\n")
print(missing_train)

cat("\nMissing from validation:\n")
print(missing_valid)

cat("\nMissing genes with names:\n")
print(
  bhot_map_clean[
    bhot_map_clean$`Entrez Gene` %in% missing_train,
    c("Original BHOT names", "Edited Gene Name", "Entrez Gene")
  ],
  row.names = FALSE
)

cat("\n============================================\n")

# ============================================================
# INSPECT REPOSITORY DOWNSTREAM B-HOT+ MODEL CODE
# ============================================================

repo_files <- list.files(
  ".",
  recursive = TRUE,
  full.names = TRUE
)

model_files <- repo_files[
  grepl(
    "BHOT|bhot|random|forest|model|predict|feature",
    basename(repo_files),
    ignore.case = TRUE
  )
]

print(model_files)

# ============================================================
# CELL 20 — Build final B-HOT+ paper-reproduction matrices
# ============================================================

feature_order <- train_names[
  train_names %in% common_bhot
]

train_bhot <- train_author[
  ,
  feature_order,
  drop = FALSE
]

test_bhot <- test_author[
  ,
  feature_order,
  drop = FALSE
]

stopifnot(
  nrow(train_bhot) == 1181,
  nrow(test_bhot) == 77,
  ncol(train_bhot) == length(feature_order),
  ncol(test_bhot) == length(feature_order),
  identical(colnames(train_bhot), colnames(test_bhot))
)

cat("Reported B-HOT+ panel size: 768\n")
cat("Measurable common B-HOT+ features:", length(feature_order), "\n\n")

cat("Final training matrix:",
    nrow(train_bhot), "x", ncol(train_bhot), "\n")

cat("Final validation matrix:",
    nrow(test_bhot), "x", ncol(test_bhot), "\n")

# ============================================================
# CELL 21 — Attach labels and save final datasets
# ============================================================

train_pheno <- read.csv(
  "Data/GSE98320.phenotype.csv",
  stringsAsFactors = FALSE,
  check.names = FALSE
)

test_pheno <- read.csv(
  "Data/GSE129166.phenotype.csv",
  stringsAsFactors = FALSE,
  check.names = FALSE
)

train_labels <- train_pheno$Label[
  match(rownames(train_bhot), train_pheno$Sample_id)
]

test_labels <- test_pheno$Label[
  match(rownames(test_bhot), test_pheno$Sample_id)
]

stopifnot(!any(is.na(train_labels)))
stopifnot(!any(is.na(test_labels)))

train_out <- data.frame(
  sample_id = rownames(train_bhot),
  diagnosis = train_labels,
  train_bhot,
  check.names = FALSE
)

test_out <- data.frame(
  sample_id = rownames(test_bhot),
  diagnosis = test_labels,
  test_bhot,
  check.names = FALSE
)

write.csv(
  train_out,
  "Data/GSE98320_BHOT_plus_AUTHOR_REPRODUCTION.csv",
  row.names = FALSE,
  quote = FALSE
)

write.csv(
  test_out,
  "Data/GSE129166_BHOT_plus_AUTHOR_REPRODUCTION.csv",
  row.names = FALSE,
  quote = FALSE
)

cat("Final datasets saved.\n")

# ============================================================
# CELL 22 — Final integrity report
# ============================================================

cat("\n============================================\n")
cat("FINAL PAPER-REPRODUCTION CHECKPOINT\n")
cat("============================================\n")

cat("GSE98320: ",
    nrow(train_bhot), " samples x ",
    ncol(train_bhot), " B-HOT+ genes\n",
    sep = "")

cat("GSE129166: ",
    nrow(test_bhot), " samples x ",
    ncol(test_bhot), " B-HOT+ genes\n",
    sep = "")

cat("\nTraining labels:\n")
print(table(train_labels))

cat("\nValidation labels:\n")
print(table(test_labels))

cat("\nFiles:\n")
print(c(
  "Data/GSE98320_BHOT_plus_AUTHOR_REPRODUCTION.csv",
  "Data/GSE129166_BHOT_plus_AUTHOR_REPRODUCTION.csv",
  "Data/combat.scaled.GSE98320.csv",
  "Data/combat.scaled.GSE129166.biopsy.csv",
  "Data/GSE98320.phenotype.csv",
  "Data/GSE129166.phenotype.csv"
))

stopifnot(
  nrow(train_bhot) == 1181,
  nrow(test_bhot) == 77,
  ncol(train_bhot) == 767,
  ncol(test_bhot) == 767
)

cat("\nPASS — ready for downstream ML work.\n")

# ============================================================
# DOWNLOAD/COPY FINAL DATASETS TO /mnt/data
# ============================================================

file.copy(
  "Data/GSE98320_BHOT_plus_AUTHOR_REPRODUCTION.csv",
  "/mnt/data/GSE98320_BHOT_plus_AUTHOR_REPRODUCTION.csv",
  overwrite = TRUE
)

file.copy(
  "Data/GSE129166_BHOT_plus_AUTHOR_REPRODUCTION.csv",
  "/mnt/data/GSE129166_BHOT_plus_AUTHOR_REPRODUCTION.csv",
  overwrite = TRUE
)

cat("Files copied to /mnt/data\n")

print(file.info(c(
  "/mnt/data/GSE98320_BHOT_plus_AUTHOR_REPRODUCTION.csv",
  "/mnt/data/GSE129166_BHOT_plus_AUTHOR_REPRODUCTION.csv"
))[, c("size", "mtime")])

# Create a ZIP containing both final datasets
zip(
  zipfile = "BHOT_plus_AUTHOR_REPRODUCTION_DATASETS.zip",
  files = c(
    "Data/GSE98320_BHOT_plus_AUTHOR_REPRODUCTION.csv",
    "Data/GSE129166_BHOT_plus_AUTHOR_REPRODUCTION.csv"
  )
)

file.info("BHOT_plus_AUTHOR_REPRODUCTION_DATASETS.zip")